name: graphylovar
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - numpy=1.20.3
  - pandas=1.3.4
  - tensorflow=2.5.0
  - spektral
  - scikit-learn
  - biopython
  - tqdm
  - pybigwig
  - networkx
  - matplotlib
  - pip
  - pip:
    - focal_loss
