name: graphylo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.20
  - pandas>=1.3
  - scikit-learn
  - biopython
  - tqdm
  - pybigwig
  - networkx>=2.6
  - matplotlib
  - pyyaml
  - pip
  - pip:
    - tensorflow>=2.6
    - spektral>=1.1
    - focal_loss
